# This file was generated by GoReleaser. DO NOT EDIT.
cask "ffmpegd" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "ffmpegd"], chdir: ".", must_succeed: false
    end
  end

  version "2.1.0"

  on_macos do
    on_arm do
      sha256 "dce8c6524dd114eb07822864cb0f9d401c18fb6594d75c4fd11b0ffea58c30f8"
      url "https://github.com/alfg/ffmpegd/releases/download/#{version}/ffmpegd_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9af052223423050baf246dd5ad6f2cfa48b8c9a487190b901dd343e7727a6a35"
      url "https://github.com/alfg/ffmpegd/releases/download/#{version}/ffmpegd_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0f6732c8be0f002a66dffe7fbc755def275e25160eba9ee33f47fae8c3a091f0"
      url "https://github.com/alfg/ffmpegd/releases/download/#{version}/ffmpegd_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ad4cc4cde4eb3812fa579512cfc50ea2577f19adf5ea99c03947a4c3d3f43e37"
      url "https://github.com/alfg/ffmpegd/releases/download/#{version}/ffmpegd_Linux_x86_64.tar.gz"
    end
  end

  name "ffmpegd"
  desc "Websocket server that runs FFmpeg encodes for FFmpeg Commander"
  homepage "https://github.com/alfg/ffmpegd"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "ffmpegd"

  # No zap stanza required
end
