# This file was generated by GoReleaser. DO NOT EDIT.
cask "ffmpegd" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "3fc7d5462ec1b909cf11dbb15172cfa279732f103285afe0b9b24a6dd3ed33da"
      url "https://github.com/alfg/ffmpegd/releases/download/0.2.0/ffmpegd_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "36b7ba8fda421c306e7e0db47e3f2a5d69e023453353fa6bc8c1ece655221059"
      url "https://github.com/alfg/ffmpegd/releases/download/0.2.0/ffmpegd_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "63db8d3abe800c50a984835e4576cde91de8df8e9035cc743d53c03283de0a9b"
      url "https://github.com/alfg/ffmpegd/releases/download/0.2.0/ffmpegd_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bc1963ffa594ce201cc70fbba1d82e081ccbebfdecfaa5837a2450ebc178b85f"
      url "https://github.com/alfg/ffmpegd/releases/download/0.2.0/ffmpegd_Linux_x86_64.tar.gz"
    end
  end

  name "ffmpegd"
  desc "Websocket server that runs FFmpeg encodes for FFmpeg Commander"
  homepage "https://github.com/alfg/ffmpegd"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "ffmpegd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ffmpegd"]
    end
  end

  # No zap stanza required
end
