# This file was generated by GoReleaser. DO NOT EDIT.
cask "ffmpegd" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "d362342cdaf47d5f94394c19454cb53ad097cec88e3d3d5bc2ed3859a6bc4e5c"
      url "https://github.com/alfg/ffmpegd/releases/download/0.2.1/ffmpegd_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cb45393a63c978d55e69d8854f3ab74a47a11272a31ef43bb39c6c304c4e3e9e"
      url "https://github.com/alfg/ffmpegd/releases/download/0.2.1/ffmpegd_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "89a148ef22f775270de01dfb73fe69ffe184bd2af513f55420fb6dfe849739ee"
      url "https://github.com/alfg/ffmpegd/releases/download/0.2.1/ffmpegd_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "53e2192bae51b94bf366f82b8793758bb63b9b8d7a7bef6a82510323ec469b3c"
      url "https://github.com/alfg/ffmpegd/releases/download/0.2.1/ffmpegd_Linux_x86_64.tar.gz"
    end
  end

  name "ffmpegd"
  desc "Websocket server that runs FFmpeg encodes for FFmpeg Commander"
  homepage "https://github.com/alfg/ffmpegd"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "ffmpegd"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "ffmpegd"], chdir: ".", must_succeed: false
    end
  end

  # No zap stanza required
end
